### DISCUSSION TITLE
Hide change codemirror language

### DISCUSSION THREAD

**Discussion by tonyctalope** [mdx-editor/editor#660] [Q&A]
Hi everyone,

Is there a way to hide or remove the top-right component that allows changing the current language or deleting the current code block?

Thanks in advance!

**Comment by tonyctalope** [comment]
As a workaround, I added the following to `global.css`:
```css
[class^="_codeMirrorToolbar"] {
  display: none;
}
```
