### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kurtschambach** [mdx-editor/editor#748]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have read the documentation and cannot find an answer.

**Describe the bug**
I don't know if I am missing something obvious, as I think other would have this problem too, but I didn't find any issues related to it.
On long code pieces in the first line, the language selector & delete icon overlap the code, and there is not really a possibility to scroll etc to see the hidden code.

**Reproduction**
Start from https://codesandbox.io/p/sandbox/mdx-editor-base-q8s7zr?file=/src/App.tsx to reproduce the problem so that I can observe the issue on my side and make sure that the fix reliably addresses it.

Reproduction: [https://codesandbox.io/p/sandbox/mdx-editor-base-forked-w2ch2d](https://codesandbox.io/p/sandbox/mdx-editor-base-forked-w2ch2d)

**To Reproduce**
1. Go to basic mdx editor exmaple
2. Add code blocks to plugins
3. write some long code in the first line
4. Language select & delete icon are overlapping code, no way to see it

**Expected behavior**
Maybe some option to hide/style the language selector box, or hide it per default in read only mode / only show on hover etc.

**Screenshots**

![Image](https://github.com/user-attachments/assets/b9fc600e-d0fc-4bda-9caa-59c25ec0cdec)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Browser: Firefox

**Comment by petyosi** [comment]
That's a valid (although not critical IMO) problem. I'm ok with hiding it in read-only mode, although the label for the code type can be useful for the user. 

Happy to accept a PR for `showToolbarOnHover`, but this might be doable with CSS only?

**Comment by makcyd** [comment]
> That's a valid (although not critical IMO) problem. I'm ok with hiding it in read-only mode, although the label for the code type can be useful for the user.
> 
> Happy to accept a PR for `showToolbarOnHover`, but this might be doable with CSS only?

We actually solved this issue by CSS and it looks as follows:

<img width="845" alt="Image" src="https://github.com/user-attachments/assets/81624fe9-c076-4f28-997f-dc48b4dd48a8" />

That's achieved with the similar code:

```scss
.#{$mdxeditor-editImageToolbar},
.#{$mdxeditor-codeMirrorToolbar} {
  visibility: hidden;
}

.#{$mdxeditor-codeMirrorWrapper} {
  overflow: visible !important;
}

.#{$mdxeditor-codeMirrorToolbar} {
  transform: translateY(calc(-100% - 1px));
}

.#{$mdxeditor-imageWrapper}:hover .#{$mdxeditor-editImageToolbar},
.#{$mdxeditor-codeMirrorWrapper}:hover .#{$mdxeditor-codeMirrorToolbar},
.#{$mdxeditor-codeMirrorWrapper}:focus-within .#{$mdxeditor-codeMirrorToolbar} {
  visibility: visible;
}
```
